baseURL: 'https://hackita.it'
languageCode: it
defaultContentLanguage: it
title: HackIta
enableRobotsTXT: true
enableEmoji: true

enableGitInfo: true

outputFormats:
  articolisitemap:
    baseName: 'sitemap'
    mediaType: 'application/xml'
    isPlainText: false
    notAlternative: true

outputs:
  section:
    - html
    - articolisitemap
    - rss