main:
  - name: Home
    pageRef: /
    weight: 10
  - name: Articoli
    pageRef: /articoli/
    weight: 20
  - name: Categorie
    pageRef: /categories/
    weight: 30
  - name: Servizi
    pageRef: /servizi/
    weight: 40
  - name: About
    pageRef: /about/
    weight: 50
footer:
  - name: Home
    pageRef: /
    weight: 10
  - name: About
    pageRef: /about/
    weight: 50
  - name: Servizi
    pageRef: /servizi/
    weight: 40
  - name: Articoli
    pageRef: /articoli/
    weight: 20
  - name: Categorie
    pageRef: /categories/
    weight: 30
  - name: Supporto
    pageRef: /supporto/
    weight: 60
