reading_speed: 170

header:
  logo: "/images/logo-wobg.png"
  cta:
    enable: true
    label: Contattami
    link: "/contact/"

footer:
  logo: "/images/logo.webp"
  disclaimer: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Modi dolorum sit rerum sint fuga perspiciatis repudiandae minus at ipsa sed qui, fugiat tempore."

social:
  facebook: "https://facebook.com"
  instagram: "https://instagram.com"
  twitter: "https://x.com"
  linkedin: "https://linkedin.com"