reading_speed: 170

header:
  logo: "/images/logo-wobg.png"
  cta:
    enable: true
    label: Contattami
    link: "/contact/"

footer:
  logo: "/images/logo.webp"

social:
  facebook: "https://facebook.com"
  instagram: "https://instagram.com"
  twitter: "https://x.com"
  linkedin: "https://linkedin.com"